@startuml CU
left to right direction
actor Usuario
actor Steam << System >>
  
Usuario --> (1. Iniciar Sesión)
(1. Iniciar Sesión) <-- Steam

Usuario --> (2. Consultar Catálogo de Videojuegos)
Usuario --> (3. Buscar y Filtrar Videojuegos)
Usuario --> (4. Consultar Ficha de Videojuego)  

Usuario --> (5. Registrar Reseña)
Usuario --> (6. Modificar Reseña Propia)
Usuario --> (7. Eliminar Reseña Propia)
Usuario --> (8. Consultar Reseñas)
  
(5. Registrar Reseña) ..> (9. Consultar Horas de Juego) : <<include>>
(9. Consultar Horas de Juego) <-- Steam
@enduml