@startuml CU
left to right direction

actor Usuario
actor Steam << System >>
  
Usuario --> (Iniciar Sesión)
(Iniciar Sesión) --> Steam

Usuario --> (Consultar Catálogo de Videojuegos)
Usuario --> (Buscar y Filtrar Videojuegos)
Usuario --> (Consultar Ficha de Videojuego)
  

Usuario --> (Registrar Reseña)
Usuario --> (Modificar Reseña Propia)
Usuario --> (Eliminar Reseña Propia)
Usuario --> (Consultar Reseñas)
  
(Registrar Reseña) ..> (Consultar Horas de Juego) : <<include>>
(Consultar Horas de Juego) --> Steam
@enduml