@startuml Casos de Uso Seminario

left to right direction

actor "Usuario" as Usuario
actor "Administrador" as Admin
actor "SteamAPI" as Steam 

usecase "1. Iniciar sesión" as CU1
usecase "2. Consultar catálogo" as CU2
usecase "5. Consultar videojuego" as CU5
usecase "6. Consultar biblioteca" as CU6
usecase "9. Modificar reseña" as CU9
usecase "13. Registrar videojuego" as CU13
usecase "14. Modificar videojuego" as CU14
usecase "15. Eliminar videojuego" as CU15
usecase "22. Autenticar usuario" as CU22

Usuario --> CU1
Usuario --> CU2
Usuario --> CU5
Usuario --> CU6
Usuario --> CU9
Admin --> CU13
Admin --> CU14
Admin --> CU15
CU22--> Steam
CU6 --> Steam
Admin --|> Usuario
CU1 ..> CU22 : <<include>>
CU9 ..> CU6 : <<include>>
@enduml