@startuml DiagramaDeComponentes

component "CapaLogicaPersistente" {
    component "GestionUsuario"{
        component "Perfil"
        component "Sesion"
        component "Usuario"
        component "PersistenciaUsuario"
        database "UsuarioDB"

        "Usuario" ..> "Perfil"
        "Usuario" ..> "Sesion"
        "PersistenciaUsuario" ..> "UsuarioDB"
        "PersistenciaUsuario" ..> "Perfil"
        "PersistenciaUsuario" ...> "Usuario"
    }

    component "GestionPublicacionYGestionReseñas" {
        component "OrganizarReseña"
        component "Reseña"
        component "PersistenciaPGR"
        database "PGRDB"
        "PersistenciaPGR" ..> "Reseña"
        "PersistenciaPGR" ..> PGRDB
        "Reseña" ..> "OrganizarReseña"
    }
    component "GestionCatalogo" {
        component "Catalogo"
        component "PersistenciaCatalogo"
        database "CatalogoDB"
        "PersistenciaCatalogo" ..> "CatalogoDB"
        "PersistenciaCatalogo" ..> "Catalogo"
    }
    component "GestionVideojuego" {
        component "Videojuego"
        component "Categoria"
        component "Etiqueta"
        component "PersistenciaVideojuego"
        database "VideojuegoDB"
        "Videojuego" ..> "Categoria"
        "Videojuego" ..> "Etiqueta"
        "PersistenciaVideojuego" ..> "Videojuego"
        "PersistenciaVideojuego" ..> "Categoria"
        "PersistenciaVideojuego" ..> "Etiqueta"
        "PersistenciaVideojuego" ..> "VideojuegoDB"
    }
}

component "CapaPresentacionWeb" {
    component "UsuariosPresentacionWeb"
    component "ReseñaPresentacionWeb"
    component "CatalogoPresentacionWeb"
    component "VideojuegoPresentacionWeb"
}

component "CapaLogicaNoPersistente" {
    component "ProcesosImportadores"{
        component "ImportadorBiblioteca"
        component "ImportadorSteamOpenID"
    }
}

"UsuariosPresentacionWeb" -(0- "GestionUsuario" : LogicaUsuarios
"ReseñaPresentacionWeb" -(0- "GestionPublicacionYGestionReseñas" : LogicaReseñas
"CatalogoPresentacionWeb" -(0- "GestionCatalogo" : LogicaCatalogo
"VideojuegoPresentacionWeb" -(0- "GestionVideojuego" : LogicaVideojuego

"GestionPublicacionYGestionReseñas" -(0- "GestionUsuario" : Autenticacion
"GestionCatalogo" -(0- "GestionUsuario" : Autenticacion
"GestionVideojuego" -(0- "GestionUsuario" : Autenticacion

"GestionCatalogo" -(0- "GestionVideojuego" : LogicaVideojuego
"Usuario" -(0- "ImportadorBiblioteca" : InformacionVideojuegosDeUsuario
"Usuario" -(0- "ImportadorSteamOpenID" : DatosCuentaSteamID

@enduml